version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: db_usernmae
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_namse
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432   

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8001:8000'   
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=DB_URL  
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  db_data:

networks:
  default:
    driver: bridge